# Generated by Django 4.2.28 on 2026-02-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_cook_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(help_text='Cooking time in minutes'),
        ),
    ]
