# Generated by Django 4.2.28 on 2026-03-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_collection_collectionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
    ]
